backend:
  name: git-gateway   # 或者 "github" / "gitlab" / "bitbucket"
  branch: main        # 你的默认分支（如 main 或 master）

media_folder: "static/uploads"   # 上传的文件存放位置
public_folder: "/uploads"        # 前端引用的路径

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
